### ISSUE TITLE
I didn't quite get the exact purpose of eq.js

### ISSUE THREAD

**Issue by renatocarvalho** [Snugug/eq.js#18]
Hi, I just saw eq.js and I curiously read all the documentation. I saw the example, but I could not understand what would be a real world use case of it. Could someone please clarify for me? Thanks

**Comment by Snugug** [comment]
`eq.js` is a JS library that provides pseudo-element query functionality specific for `width` queries. This allows components to be built that respond to their own size instead of the viewport a size, meaning they can be used in multiple places in multiple layouts without changing markup or styling.

**Comment by renatocarvalho** [comment]
Now I got it! Thanks!
