### ISSUE TITLE
Let us use "em" values for element query values

### ISSUE THREAD

**Issue by nhoizey** [Snugug/eq.js#5]
It is a good practice to use "em" for global media queries, so it would be nice to have this in element queries too.

**Comment by Snugug** [comment]
While I'm fully on board for using `em` values for media queries, I'm fairly firmly against it for element queries, and I'll tell you why; they don't make sense.

The reason to use `em` values for media queries is that browsers natively know the viewport size in `em` and `px`, this conversion done based on the root user font size and defaults to a nifty and standard (standard being the key here) conversion rate of `1em == 16px`. That's why we built the option into [Breakpoint](https://github.com/Team-Sass/breakpoint). It's a best practice for media queries because it allows for all browsers to have media queries trigger when the base font size changes, which gives users an ideal experience regardless of what their zoom level was. Fantastic. Browsers mostly do the same for `px` based media queries now too, but there are old devices and browsers out there that may not and future devices that likewise may not, so it's still a best practice.

Now, on the other hand, the element queries in **eq.js** rely upon rendered measurements of a component's width through JavaScript. This is exclusively returned in `px`, and is accurate no matter what zoom level as it does an actual measurement. The reason this isn't returned in `em` is that value would change drastically depending on standard `em` scaling, which makes that `em` value a moving target useless to query against whereas its always the same `px` value. This is the key difference: in media queries, the conversion is static making it practical, here it would be dynamic. Because of that, either the query would need to be converted to `em` based on the full DOM tree, or the width would need to be converted using the same reasoning. Even then it would be inaccurate; an element whose width is `500px` would have different `em` values if the font size was `12px` or `16px`, but its width wouldn't have changed; so at the end of the day we would want the `px` value either way. While this could be avoided by setting the same ratio used in media queries, I'm hesitant to do that as the width of a rendered element in `em` already has a meaning, and this would be a new, distinct, and incompatible meaning.

With this being said, I'm open to someone trying changing my mind, so I'll leave this open for a little bit, but if a convincing argument that doesn't confuse element width in element queries with actual element width and doesn't add a large amount of code to the codebase isn't found within 10 days, I'm going to close this issue.

**Comment by Snugug** [comment]
Seeing no further discussion on this, I'm closing this issue.
