### ISSUE TITLE
Queries doesnt work when container width changed

### ISSUE THREAD

**Issue by lasekio** [Snugug/eq.js#58]

**Comment by jacobjuul** [comment]
https://github.com/Snugug/eq.js/pull/61 does this solve your issue?

**Comment by Snugug** [comment]
[They never have, by design](https://github.com/Snugug/eq.js#technical-mumbo-jumbo).

> This script very consciously does not and will not attempt to recalculate element queries on all DOM changes as that is very likely to result in a never-ending rabbit hole of craziness.

Running **eq.js** every time a container width changes is A) terrible for performance and B) likely to lead to infinite loop issues, one of the main things holding it back from browser implementation. Instead, **eq.js** [provides[(https://github.com/Snugug/eq.js#usage) `eqjs.query(nodes)` to allow you to recalculate and reapply the querying when you know want.
